### ISSUE TITLE
All install attempts fail on AlmaLinux 9

### ISSUE THREAD

**Issue by codelabyz** [hoophq/hoop#465]
==== Running Docker Compose ====
Starting containers... (This may take a while)
WARNING: The HOOP_TLS_MODE variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
'name' does not match any of the regexes: '^x-'

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
✘ Failed to run docker compose

It won't run anything and just fails.

**Comment by sandromello** [comment]
Hey @codelabyz , we just launched an update that broken this setup from the website. Follow this guide instead for the moment:
https://hoop.dev/docs/getting-started/installation/docker-compose

**Comment by sandromello** [comment]
We've updated our documentation, and it should be working now. Let me know if you find any issues.
