### ISSUE TITLE
How to make it work behing NGINX Proxy Manager

### ISSUE THREAD

**Issue by Rubik-AU** [hoophq/hoop#505]
Hey team,

I'm having difficulty setting up Hoop over NPM because I'm receiving the following error:

`Mixed Content: The page at 'https://mydomain' was loaded over HTTPS, but requested an insecure stylesheet 'http://myip/css/site.css'. This request has been blocked; the content must be served over HTTPS.`

It is self-hosted using the Docker Compose file from the website. I also want to use the Cloudflare Zero Trust solution to access the site, but I’m encountering the same error.

Is there any solution to serve the URL over HTTPS, or can I set up Let's Encrypt?

**Comment by mtmr0x** [comment]
hey @Rubik-AU, note that the Docker Compose might need some tweaks to work best in production. We didn't add to it any volume to improve the performance of some actions, but still, it's totally possible to use it, and if you don't face any performance issues, you will be fine.

Regarding the protocol issue you are facing, make sure the env var `API_URL` is set to the full domain you will serve our Gateway. If you set it as your IP and then make a DNS configuration to port forward to your IP (not saying that this is exactly the case, but it looked like to be according to your comment. Let me know if anything), the assets for the webapp will be served with the `API_URL` schema. So add to the `API_URL` the full schema and host that will be served with https, and it should work. If not, please provide a bit more info on the .env file and how you configured the `API_URL` value. 

If you didn't configure it at all, it will use a 127.0.0.1 default that will serve inside your VM IP. To add it, open the `.env` file and add this value there.

**Comment by Rubik-AU** [comment]
Hi @mtmr0x,

Thanks, it is working now.

After swapping `API_URL` to my domain name, I basically removed the port and left it as `https://mydomain`. 

I haven’t noticed any performance issues. Currently, I have 8 instances to manage, so I don't think that will be an issue.

**Comment by mtmr0x** [comment]
I'm happy to know that! I will take this to our team so we can iterate on your onboarding and create an even better product. 

Closing this. If you find any other issue, feel free to open another issue here. Cheers
