### ISSUE TITLE
Can't remove connections that are offline

### ISSUE THREAD

**Issue by corvusmod** [hoophq/hoop#534]
When a connection is online you can go to the configuration and delete it.
When a connection is offline, you can't do it, so there is no way to delete if from the UI

![image](https://github.com/user-attachments/assets/924fd87c-0f1e-41b7-92b9-13318169be40)

**Comment by sandromello** [comment]
Hey @corvusmod , this happens when a connection is created via `hoop run` only. We're working on to fix this issue.
As an alternative you can use the hoop command line to delete the connection:

```sh
hoop admin delete conn python-test
```

**Comment by rogefm** [comment]
Hey @corvusmod, starting from version 1.30.1, you can now delete these connections directly in the web app as well! 😊
Thanks for bringing this up.
