### ISSUE TITLE
[BUG-MAYBE] Password field is not hidden on web ui login

### ISSUE THREAD

**Issue by buzzzo** [hoophq/hoop#546]
![Screenshot 2024-11-13 at 11 27 09](https://github.com/user-attachments/assets/fd1e9e2e-1f00-4635-93b2-c4dec5850c61)

**Comment by mtmr0x** [comment]
@buzzzo thanks for sharing this feedback with us. We addressed the discussion for that internally to make the proper adjustments. In a couple days it should be solved. Originally it's not a bug, but I understand how it looks like one. We will make the proper adjustments and release this change. If you want to follow this thread, I've related the PR #581 to this.

Again, thanks for raising this 🎉
