### ISSUE TITLE
[BUG] Organisation ID

### ISSUE THREAD

**Issue by daanpersoons** [hoophq/hoop#554]
I self-host hoop in K8S with a custom postgres database.
To create an API key I need to have my org-id [according to the docs](https://hoop.dev/docs/learn/api-key-usage#pre-requisites), however there is no possibility to get the org-id anywhere.

`hoop admin get orgkeys` only returns the key, not the ID.

The AI bot told me to do the [api call](https://hoop.dev/docs/api-reference/core/get-org-key) to get it, but this is not possible without being able to create an API key.

How I would solve this: make the org-id available in the UI or through a cli command.

How I fixed my Issue: Connected to the DB myself and retreived the org-id out of there.

Keep up the great work, awesome tool, thanks! ❤️

**Comment by sandromello** [comment]
Hey @daanpersoons , Thank you for the feedback and the issue report.
You could use the command line to obtain the organization id:

```sh
hoop admin get userinfo -o json
```
