### ISSUE TITLE
Using API_KEY

### ISSUE THREAD

**Issue by buzzzo** [hoophq/hoop#580]
I'm playing aroung api access.

1) First question coming from the API_KEY format.
In the doc: is described as <org_id>|<random_string.
Does <org_id> is something predefined in the instance or could i choose whatever i want ?
Does something like: foobar|123456 could work ?

2) Second question: should i recreate the container when i add the api_key env var in .ev file or a restart is enough ?

3) I'm unsing for testing the following curl syntax: 
curl --request GET --url https://hoop.foo.com/api/connections --header "Api-Key: foobar|123456"
But I receive everytime: {"message":"unauthorized"}%

What do I miss ?

Thx

**Comment by buzzzo** [comment]
I figure out the issue.

First: orgid is something fixed and could be detected from the gateway container logs.
So just to respond to myself: org id is FIXED.

Maybe would be good to update documentation about api_key.

Thx

**Comment by sandromello** [comment]
Hi Davide,

Thank you for the feedback, we've updated the [documentation](https://hoop.dev/docs/learn/api-key-usage) with more details about how to setup the api key
