### ISSUE TITLE
Updating connection with guard rail gives an error

### ISSUE THREAD

**Issue by djbe** [hoophq/hoop#617]
When a connection as an associated guard rail, and you try to edit that connection again (without touching the guard rail field), saving fails with the error:
> failed creating guard rail association, reason=ERROR: invalid input syntax for type uuid: "" (SQLSTATE 22P02)

If you re-select the guard rail(s) in the form, and then save, everything works fine.

<details>
<summary>Full stack trace in k8s (click to expand)</summary>

> github.com/hoophq/hoop/gateway/api/connections.Put
> 	/home/runner/work/hoop/hoop/gateway/api/connections/connections.go:197
> github.com/gin-gonic/gin.(*Context).Next
> 	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
> github.com/hoophq/hoop/gateway/api.(*Api).buildRoutes.(*Api).TrackRequest.func10
> 	/home/runner/work/hoop/hoop/gateway/api/middleware.go:87
> github.com/gin-gonic/gin.(*Context).Next
> 	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
> github.com/hoophq/hoop/gateway/api/apiroutes.(*Router).setUserContext
> 	/home/runner/work/hoop/hoop/gateway/api/apiroutes/auth.go:133
> github.com/hoophq/hoop/gateway/api/apiroutes.(*Router).AuthMiddleware
> 	/home/runner/work/hoop/hoop/gateway/api/apiroutes/auth.go:118
> github.com/gin-gonic/gin.(*Context).Next
> 	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
> github.com/hoophq/hoop/gateway/api/apiroutes.AdminOnlyAccessRole
> 	/home/runner/work/hoop/hoop/gateway/api/apiroutes/roles.go:50
> github.com/gin-gonic/gin.(*Context).Next
> 	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
> go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin.Middleware.func1
> 	/home/runner/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin@v0.49.0/gintrace.go:95
> github.com/gin-gonic/gin.(*Context).Next
> 	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
> github.com/getsentry/sentry-go/gin.(*handler).handle
> 	/home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.18.0/gin/sentrygin.go:57
> github.com/gin-gonic/gin.(*Context).Next
> 	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
> github.com/hoophq/hoop/gateway/api.(*Api).StartAPI.CORSMiddleware.func2
> 	/home/runner/work/hoop/hoop/gateway/api/middleware.go:120
> github.com/gin-gonic/gin.(*Context).Next
> 	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
> github.com/hoophq/hoop/gateway/api.(*Api).StartAPI.RecoveryWithZap.CustomRecoveryWithZap.func4
> 	/home/runner/go/pkg/mod/github.com/gin-contrib/zap@v0.2.0/zap.go:159
> github.com/gin-gonic/gin.(*Context).Next
> 	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
> github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
> 	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
> github.com/gin-gonic/gin.(*Engine).ServeHTTP
> 	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
> net/http.serverHandler.ServeHTTP
> 	/opt/hostedtoolcache/go/1.23.4/x64/src/net/http/server.go:3210
> net/http.(*conn).serve
> 	/opt/hostedtoolcache/go/1.23.4/x64/src/net/http/server.go:2092

</details>

Some more info:
- Using the web admin interface.
- webapp version 1.35.1
- gateway version 1.31.10

**Comment by rogefm** [comment]
This issue has been resolved in 95d2f7d17dfd148d61d991d6eea27f916a987c36

And will be available in the version 1.31.12
